var express = require('express')
var router = express.Router()
var Forum = require('../controllers/forum')
var Filter = require('../controllers/filter')

router.get('/wxoauth', Forum.wxoauth)
router.get('/user', Filter.login, Forum.info)
router.get('/user/favorites', Filter.login, Forum.favorites)
router.get('/post', Forum.getPost)
router.delete('/post', Filter.admin, Forum.delPost)
router.post('/post', Filter.login, Forum.insertPost)
router.patch('/post', Filter.login, Forum.favorPost)
router.post('/post/operate', Filter.admin, Forum.postOperate)
router.get('/posts/firstPage', Forum.getFirstPagePosts)
router.get('/posts/nextPage', Forum.getNextPagePosts)
router.get('/posts/reply/firstPage', Forum.getFirstPageReplyPosts)
router.get('/posts/reply/nextPage', Forum.getNextPagePosts)
router.post('/comment', Filter.login, Forum.insertComment)

module.exports = router
